### PR TITLE
Add NtSystemDebugControl hook

### PR DESCRIPTION
**Pull request by Mattiwatti**
This should fix issue #1. I'm sure the hook isn't perfect as there are 32 possible SYSDBG_COMMAND values (probably more in newer Windows versions) so the exact return behaviour may differ depending on the input, but 99% of anti-debugger checks will simply do
```C++
bool debuggerPresent = ZwSystemDebugControl(0, NULL, 0, NULL, 0, NULL) != STATUS_DEBUGGER_INACTIVE;
```
anyway.

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks!

**Comment by mrexodia** [comment]
I added some code for Windows 10 6.3.9600.18438 it should be able to find the SSDT again but I couldn't test it.

**Comment by Mattiwatti** [comment]
This doesn't work for me on 6.3.9600.14393.206. I don't have a .18xxx version to try, is that the insider preview thingy?

Found SSDT is 0xFFFFFFFFFFE5605D (invalid, fails first check), actual address is 0xFFFFF800761C2740. The RVA is -1744803 (decimal) vs 0x3A7740 actual, I'm guessing that doesn't help...

I do have the same two xmmword cmp's in KeAddSystemServiceTable (or actually 3, but the third is for the win32k.sys table if I'm not mistaken).

**Comment by mrexodia** [comment]
I will try to load the driver on my Windows 10 VM another time and see what happens...

**Comment by mrexodia** [comment]
Could you post the hex dump /+ disassembly for those compares?

**Comment by Mattiwatti** [comment]
Sure. I tried to get the hex dump inline with the assembly, but there doesn't seem to be any option for it in IDA :/

```asm
PAGE:00000001405516C8 ; BOOLEAN __stdcall KeAddSystemServiceTable(PULONG_PTR Base, PULONG Count, ULONG Limit, PUCHAR Number, ULONG Index)
PAGE:00000001405516C8                 public KeAddSystemServiceTable
PAGE:00000001405516C8 KeAddSystemServiceTable proc near       ; DATA XREF: .edata:off_140730028↓o
PAGE:00000001405516C8
PAGE:00000001405516C8 arg_0           = qword ptr  8
PAGE:00000001405516C8 arg_8           = qword ptr  10h
PAGE:00000001405516C8 arg_10          = qword ptr  18h
PAGE:00000001405516C8 Index           = dword ptr  28h
PAGE:00000001405516C8
PAGE:00000001405516C8                 mov     [rsp+arg_0], rbx
PAGE:00000001405516CD                 mov     [rsp+arg_8], rsi
PAGE:00000001405516D2                 mov     [rsp+arg_10], rdi
PAGE:00000001405516D7                 mov     edx, [rsp+Index]
PAGE:00000001405516DB                 mov     r10, r9
PAGE:00000001405516DE                 mov     ebx, r8d
PAGE:00000001405516E1                 mov     r11, rcx
PAGE:00000001405516E4                 lea     eax, [rdx-1]
PAGE:00000001405516E7                 cmp     eax, 1
PAGE:00000001405516EA                 ja      loc_14055181A
PAGE:00000001405516F0                 xor     r9d, r9d
PAGE:00000001405516F3                 cmp     edx, 2
PAGE:00000001405516F6                 jz      loc_140551786
PAGE:00000001405516FC                 cmp     qword ptr cs:xmmword_1403A7760, r9
PAGE:0000000140551703                 jnz     loc_14055181A
PAGE:0000000140551709                 cmp     qword ptr cs:xmmword_1403A7720, r9
PAGE:0000000140551710                 jnz     loc_14055181A
PAGE:0000000140551716                 cmp     edx, 1
PAGE:0000000140551719                 jnz     short loc_140551793
PAGE:000000014055171B                 mov     edi, cs:KiTableInformation
PAGE:0000000140551721                 lea     rax, __ImageBase
PAGE:0000000140551728                 mov     cs:qword_1403A7738, r10
PAGE:000000014055172F                 lea     r10d, rva xmmword_1403A7720[rax]
PAGE:0000000140551736                 add     r10d, edi
PAGE:0000000140551739                 mov     qword ptr cs:xmmword_1403A7720, rcx
PAGE:0000000140551740                 add     r10d, ecx
PAGE:0000000140551743                 mov     cs:dword_1403A7730, ebx
PAGE:0000000140551749                 test    ebx, ebx
PAGE:000000014055174B                 jz      short loc_140551777
PAGE:000000014055174D                 mov     rsi, rcx
PAGE:0000000140551750
PAGE:0000000140551750 loc_140551750:                          ; CODE XREF: KeAddSystemServiceTable+AD↓j
PAGE:0000000140551750                 movsxd  rdx, dword ptr [rsi]
PAGE:0000000140551753                 lea     r8d, [r9+1]
PAGE:0000000140551757                 mov     rax, rdx
PAGE:000000014055175A                 lea     rsi, [rsi+4]
PAGE:000000014055175E                 sar     rax, 4
PAGE:0000000140551762                 mov     r9d, r8d
PAGE:0000000140551765                 mov     ecx, [rax+r11]
PAGE:0000000140551769                 add     ecx, edx
PAGE:000000014055176B                 xor     r10d, ecx
PAGE:000000014055176E                 imul    r10d, r8d
PAGE:0000000140551772                 cmp     r8d, ebx
PAGE:0000000140551775                 jb      short loc_140551750
PAGE:0000000140551777
PAGE:0000000140551777 loc_140551777:                          ; CODE XREF: KeAddSystemServiceTable+83↑j
PAGE:0000000140551777                 lea     eax, [rdi+r10*2]
PAGE:000000014055177B                 mov     cs:KiTableInformation, eax
PAGE:0000000140551781                 jmp     loc_140551816
PAGE:0000000140551786 ; ---------------------------------------------------------------------------
PAGE:0000000140551786
PAGE:0000000140551786 loc_140551786:                          ; CODE XREF: KeAddSystemServiceTable+2E↑j
PAGE:0000000140551786                 cmp     qword ptr cs:xmmword_1403A77A0, r9
PAGE:000000014055178D                 jnz     loc_14055181A
PAGE:0000000140551793
PAGE:0000000140551793 loc_140551793:                          ; CODE XREF: KeAddSystemServiceTable+51↑j
PAGE:0000000140551793                 lea     rax, __ImageBase
PAGE:000000014055179A                 lea     ecx, [rdx-1]
PAGE:000000014055179D                 shl     rcx, 5
PAGE:00000001405517A1                 mov     [rcx+rax+3A7780h], r11
PAGE:00000001405517A9                 mov     [rcx+rax+3A7790h], ebx
PAGE:00000001405517B0                 mov     [rcx+rax+3A7798h], r10
PAGE:00000001405517B8                 cmp     edx, 2
PAGE:00000001405517BB                 jnz     short loc_140551816
PAGE:00000001405517BD                 mov     r11, qword ptr cs:xmmword_1403A77A0
PAGE:00000001405517C4                 lea     rax, xmmword_1403A77A0
PAGE:00000001405517CB                 mov     ebx, cs:KiTableInformation
PAGE:00000001405517D1                 mov     esi, dword ptr cs:xmmword_1403A77B0
PAGE:00000001405517D7                 lea     r10d, [rbx+r11]
PAGE:00000001405517DB                 add     r10d, eax
PAGE:00000001405517DE                 test    esi, esi
PAGE:00000001405517E0                 jz      short loc_14055180C
PAGE:00000001405517E2                 mov     rdi, r11
PAGE:00000001405517E5
PAGE:00000001405517E5 loc_1405517E5:                          ; CODE XREF: KeAddSystemServiceTable+142↓j
PAGE:00000001405517E5                 movsxd  rdx, dword ptr [rdi]
PAGE:00000001405517E8                 lea     r8d, [r9+1]
PAGE:00000001405517EC                 mov     rax, rdx
PAGE:00000001405517EF                 lea     rdi, [rdi+4]
PAGE:00000001405517F3                 sar     rax, 4
PAGE:00000001405517F7                 mov     r9d, r8d
PAGE:00000001405517FA                 mov     ecx, [rax+r11]
PAGE:00000001405517FE                 add     ecx, edx
PAGE:0000000140551800                 xor     r10d, ecx
PAGE:0000000140551803                 imul    r10d, r8d
PAGE:0000000140551807                 cmp     r8d, esi
PAGE:000000014055180A                 jb      short loc_1405517E5
PAGE:000000014055180C
PAGE:000000014055180C loc_14055180C:                          ; CODE XREF: KeAddSystemServiceTable+118↑j
PAGE:000000014055180C                 lea     ecx, [rbx+r10*2]
PAGE:0000000140551810                 mov     cs:KiTableInformation, ecx
PAGE:0000000140551816
PAGE:0000000140551816 loc_140551816:                          ; CODE XREF: KeAddSystemServiceTable+B9↑j
PAGE:0000000140551816                                         ; KeAddSystemServiceTable+F3↑j
PAGE:0000000140551816                 mov     al, 1
PAGE:0000000140551818                 jmp     short loc_14055181C
PAGE:000000014055181A ; ---------------------------------------------------------------------------
PAGE:000000014055181A
PAGE:000000014055181A loc_14055181A:                          ; CODE XREF: KeAddSystemServiceTable+22↑j
PAGE:000000014055181A                                         ; KeAddSystemServiceTable+3B↑j ...
PAGE:000000014055181A                 xor     al, al
PAGE:000000014055181C
PAGE:000000014055181C loc_14055181C:                          ; CODE XREF: KeAddSystemServiceTable+150↑j
PAGE:000000014055181C                 mov     rbx, [rsp+arg_0]
PAGE:0000000140551821                 mov     rsi, [rsp+arg_8]
PAGE:0000000140551826                 mov     rdi, [rsp+arg_10]
PAGE:000000014055182B                 retn
PAGE:000000014055182B KeAddSystemServiceTable endp
```
Hex:
48895C2408488974241048897C24188B5424284D8BD1418BD84C8BD98D42FF83F8010F872A0100004533C983FA020F848A0000004C390D5D60E5FF0F85110100004C390D1060E5FF0F850401000083FA0175788B3D1761DAFF488D05D8E8AAFF4C89150960E5FF448D9020773A004403D748890DE05FE5FF4403D1891DE75FE5FF85DB742A488BF1486316458D4101488BC2488D760448C1F804458BC8428B0C1803CA4433D1450FAFD0443BC372D9428D04578905B760DAFFE9900000004C390D1360E5FF0F8587000000488D0566E8AAFF8D4AFF48C1E1054C899C0180773A00899C0190773A004C89940198773A0083FA0275594C8B1DDC5FE5FF488D05D55FE5FF8B1D6760DAFF8B35D95FE5FF468D141B4403D085F6742A498BFB486317458D4101488BC2488D7F0448C1F804458BC8428B0C1803CA4433D1450FAFD0443BC672D9428D0C53890D2260DAFFB001EB0232C0488B5C2408488B742410488B7C2418C3

**Comment by Mattiwatti** [comment]
I forgot about our lord and saviour WinDbg. This should be more helpful.
```asm
nt!KeAddSystemServiceTable:
fffff801`775516c8 48895c2408      mov     qword ptr [rsp+8],rbx
fffff801`775516cd 4889742410      mov     qword ptr [rsp+10h],rsi
fffff801`775516d2 48897c2418      mov     qword ptr [rsp+18h],rdi
fffff801`775516d7 8b542428        mov     edx,dword ptr [rsp+28h]
fffff801`775516db 4d8bd1          mov     r10,r9
fffff801`775516de 418bd8          mov     ebx,r8d
fffff801`775516e1 4c8bd9          mov     r11,rcx
fffff801`775516e4 8d42ff          lea     eax,[rdx-1]
fffff801`775516e7 83f801          cmp     eax,1
fffff801`775516ea 0f872a010000    ja      nt!KeAddSystemServiceTable+0x152 (fffff801`7755181a)
fffff801`775516f0 4533c9          xor     r9d,r9d
fffff801`775516f3 83fa02          cmp     edx,2
fffff801`775516f6 0f848a000000    je      nt!KeAddSystemServiceTable+0xbe (fffff801`77551786)
fffff801`775516fc 4c390d5d60e5ff  cmp     qword ptr [nt!KeServiceDescriptorTable+0x20 (fffff801`773a7760)],r9
fffff801`77551703 0f8511010000    jne     nt!KeAddSystemServiceTable+0x152 (fffff801`7755181a)
fffff801`77551709 4c390d1060e5ff  cmp     qword ptr [nt!KeServiceDescriptorTableShadow+0x20 (fffff801`773a7720)],r9
fffff801`77551710 0f8504010000    jne     nt!KeAddSystemServiceTable+0x152 (fffff801`7755181a)
fffff801`77551716 83fa01          cmp     edx,1
fffff801`77551719 7578            jne     nt!KeAddSystemServiceTable+0xcb (fffff801`77551793)
fffff801`7755171b 8b3d1761daff    mov     edi,dword ptr [nt!KiTableInformation (fffff801`772f7838)]
fffff801`77551721 488d05d8e8aaff  lea     rax,[nt!WerLiveKernelInitSystem <PERF> (nt+0x0) (fffff801`77000000)]
fffff801`77551728 4c89150960e5ff  mov     qword ptr [nt!KeServiceDescriptorTableShadow+0x38 (fffff801`773a7738)],r10
fffff801`7755172f 448d9020773a00  lea     r10d,[rax+3A7720h]
fffff801`77551736 4403d7          add     r10d,edi
fffff801`77551739 48890de05fe5ff  mov     qword ptr [nt!KeServiceDescriptorTableShadow+0x20 (fffff801`773a7720)],rcx
fffff801`77551740 4403d1          add     r10d,ecx
fffff801`77551743 891de75fe5ff    mov     dword ptr [nt!KeServiceDescriptorTableShadow+0x30 (fffff801`773a7730)],ebx
fffff801`77551749 85db            test    ebx,ebx
fffff801`7755174b 742a            je      nt!KeAddSystemServiceTable+0xaf (fffff801`77551777)
fffff801`7755174d 488bf1          mov     rsi,rcx
fffff801`77551750 486316          movsxd  rdx,dword ptr [rsi]
fffff801`77551753 458d4101        lea     r8d,[r9+1]
fffff801`77551757 488bc2          mov     rax,rdx
fffff801`7755175a 488d7604        lea     rsi,[rsi+4]
fffff801`7755175e 48c1f804        sar     rax,4
fffff801`77551762 458bc8          mov     r9d,r8d
fffff801`77551765 428b0c18        mov     ecx,dword ptr [rax+r11]
fffff801`77551769 03ca            add     ecx,edx
fffff801`7755176b 4433d1          xor     r10d,ecx
fffff801`7755176e 450fafd0        imul    r10d,r8d
fffff801`77551772 443bc3          cmp     r8d,ebx
fffff801`77551775 72d9            jb      nt!KeAddSystemServiceTable+0x88 (fffff801`77551750)
fffff801`77551777 428d0457        lea     eax,[rdi+r10*2]
fffff801`7755177b 8905b760daff    mov     dword ptr [nt!KiTableInformation (fffff801`772f7838)],eax
fffff801`77551781 e990000000      jmp     nt!KeAddSystemServiceTable+0x14e (fffff801`77551816)
fffff801`77551786 4c390d1360e5ff  cmp     qword ptr [nt!KeServiceDescriptorTableFilter+0x20 (fffff801`773a77a0)],r9
fffff801`7755178d 0f8587000000    jne     nt!KeAddSystemServiceTable+0x152 (fffff801`7755181a)
fffff801`77551793 488d0566e8aaff  lea     rax,[nt!WerLiveKernelInitSystem <PERF> (nt+0x0) (fffff801`77000000)]
fffff801`7755179a 8d4aff          lea     ecx,[rdx-1]
fffff801`7755179d 48c1e105        shl     rcx,5
fffff801`775517a1 4c899c0180773a00 mov     qword ptr [rcx+rax+3A7780h],r11
fffff801`775517a9 899c0190773a00  mov     dword ptr [rcx+rax+3A7790h],ebx
fffff801`775517b0 4c89940198773a00 mov     qword ptr [rcx+rax+3A7798h],r10
fffff801`775517b8 83fa02          cmp     edx,2
fffff801`775517bb 7559            jne     nt!KeAddSystemServiceTable+0x14e (fffff801`77551816)
fffff801`775517bd 4c8b1ddc5fe5ff  mov     r11,qword ptr [nt!KeServiceDescriptorTableFilter+0x20 (fffff801`773a77a0)]
fffff801`775517c4 488d05d55fe5ff  lea     rax,[nt!KeServiceDescriptorTableFilter+0x20 (fffff801`773a77a0)]
fffff801`775517cb 8b1d6760daff    mov     ebx,dword ptr [nt!KiTableInformation (fffff801`772f7838)]
fffff801`775517d1 8b35d95fe5ff    mov     esi,dword ptr [nt!KeServiceDescriptorTableFilter+0x30 (fffff801`773a77b0)]
fffff801`775517d1 8b35d95fe5ff    mov     esi,dword ptr [nt!KeServiceDescriptorTableFilter+0x30 (fffff801`773a77b0)]
fffff801`775517d7 468d141b        lea     r10d,[rbx+r11]
fffff801`775517db 4403d0          add     r10d,eax
fffff801`775517de 85f6            test    esi,esi
fffff801`775517e0 742a            je      nt!KeAddSystemServiceTable+0x144 (fffff801`7755180c)
fffff801`775517e2 498bfb          mov     rdi,r11
fffff801`775517e5 486317          movsxd  rdx,dword ptr [rdi]
fffff801`775517e8 458d4101        lea     r8d,[r9+1]
fffff801`775517ec 488bc2          mov     rax,rdx
fffff801`775517ef 488d7f04        lea     rdi,[rdi+4]
fffff801`775517f3 48c1f804        sar     rax,4
fffff801`775517f7 458bc8          mov     r9d,r8d
fffff801`775517fa 428b0c18        mov     ecx,dword ptr [rax+r11]
fffff801`775517fe 03ca            add     ecx,edx
fffff801`77551800 4433d1          xor     r10d,ecx
fffff801`77551803 450fafd0        imul    r10d,r8d
fffff801`77551807 443bc6          cmp     r8d,esi
fffff801`7755180a 72d9            jb      nt!KeAddSystemServiceTable+0x11d (fffff801`775517e5)
fffff801`7755180c 428d0c53        lea     ecx,[rbx+r10*2]
fffff801`77551810 890d2260daff    mov     dword ptr [nt!KiTableInformation (fffff801`772f7838)],ecx
fffff801`77551816 b001            mov     al,1
fffff801`77551818 eb02            jmp     nt!KeAddSystemServiceTable+0x154 (fffff801`7755181c)
fffff801`7755181a 32c0            xor     al,al
fffff801`7755181c 488b5c2408      mov     rbx,qword ptr [rsp+8]
fffff801`77551821 488b742410      mov     rsi,qword ptr [rsp+10h]
fffff801`77551826 488b7c2418      mov     rdi,qword ptr [rsp+18h]
fffff801`7755182b c3              ret
```

**Comment by mrexodia** [comment]
options for future reference 👍 thanks!

**Pull request merged**
